### ISSUE TITLE
Passwords for signin

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#44]
I guess the decision was made to limit passwords to be only 4 characters long? From what I understand you guys wanted to include a password to add security, but imposing such a counter intuitive restriction works against that in a pretty big way, if we stick with password authentication, this password restriction is going to need to be reevaluated.

Also, when I entered a password that did not satisfy these requirements, I was only told what was wrong with my password if I happened to have the password textbox highlighted when I pressed checkin (which is a very uncommon scenario for the most common use case), all the other times it would just pop up the exclaimation mark, but not tell me the problem with the password, so there is come inconsistancy with when this warning comes up that needs to be addressed.

**Comment by nelalison** [comment]
fixed

**Comment by symbyte** [comment]
Please dont just say "fixed" when you fix something. You need to tell us what was changed so that we know what is going on. Please don't make us hunt through your code to see what is different.

**Comment by symbyte** [comment]
Case in point: This issue says that having a max length of 4 for a password is very insecure. Your fix does not change this and thus does not fix one of the main points of the issue.

**Comment by nelalison** [comment]
Do you want me to increase the password limit or set a minimum password?

**Comment by symbyte** [comment]
I don't understand what you mean when you say "set a minimum password". 
I'm just saying that users need to be able to have passwords that are 
longer than 4 characters.

**Comment by symbyte** [comment]
second paragraph fixed in #59, still waiting for fix on password length before closing.

**Comment by symbyte** [comment]
being addressed in #65, closing
